dist: focal
sudo: false
language: python

python:
  - "3.13"

before_install:
  - pip3 install setuptools==80.9.0
  - python3 setup.py install
  - pip install pytest-codecov

script:
  - pytest --cov-report term --cov-report xml:coverage.xml --cov=copilot_auth tests/test_auth.py
  - curl -Os https://uploader.codecov.io/latest/linux/codecov && chmod +x codecov && ./codecov -t 98a19ccc-20be-4af6-9c61-0163b5110abb

notifications:
  email: false